[project]
name = "pkg-second"
version = "0.1.0"
description = "Second package"
authors = [
    {name = "John Doe", email = "johndoe@example.org"},
]
dependencies = ["pkg-core[http] @ file:///${PROJECT_ROOT}/../pkg-core"]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
